//
// Created by megaxela on 27.02.17.
//

#ifndef FRTESTER_DOCUMENTHEADERPRINTTESTACTION_H
#define FRTESTER_DOCUMENTHEADERPRINTTESTACTION_H


class DocumentHeaderPrintTestAction
{

};


#endif //FRTESTER_DOCUMENTHEADERPRINTTESTACTION_H
