//
// Created by megaxela on 27.02.17.
//

#ifndef FRTESTER_SHIFTREPORTWITHOUTEXTINCTIONTESTACTION_H
#define FRTESTER_SHIFTREPORTWITHOUTEXTINCTIONTESTACTION_H


class ShiftReportWithoutExtinctionTestAction
{

};


#endif //FRTESTER_SHIFTREPORTWITHOUTEXTINCTIONTESTACTION_H
